name: Coverage check on pull request to develop/main

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
    branches:
        - develop
        - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn install

      - name: Run tests
        run: |
          yarn test --coverage

      - name: Add coverage comment
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: |
          echo "Coverage: ${{ steps.test.outputs.coverage }}" | tee coverage.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "Coverage report: https://codecov.io/gh/${{ github.repository }}/commit/${{ github.sha }}"
        