name: Deploy Hatch-A-Cab Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # We will deploy with only one version of node  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: test coverage check
        run: npm run coverage
      
      - name: stylelint checks
        run: npm run lint

  secret-scanning: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: 'Talisman Secret scanning'
        run: |
          git reset --soft HEAD~$(($(git rev-list --count --first-parent HEAD) - 1))
          curl -L -O https://github.com/thoughtworks/talisman/releases/download/v1.23.0/talisman_linux_386
          chmod +x talisman_linux_386
          ./talisman_linux_386 --githook pre-commit || exit 1

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build_test, secret-scanning]
    steps:
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}